### ISSUE TITLE
Switch from gfplot to gfdata and move internal data into gfiphc

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfiphc#13]

**Comment by andrew-edwards** [comment]
Done the switch. No reference to `gfplot` now, just had to comment out `gfplot::plot_survey_index()` to avoid Importing `gfplot` (which has lots of dependencies). Still to do:

- [x] check internal data is all in gfiphc
- [ ] test examples of functions
- [x] make a vignette - could use code written for Beau
- [x] make a simpler `plot_survey_index()` plotting function to include in here (and not rely on `gfplot`).

**Comment by andrew-edwards** [comment]
Several vignettes now done, lots of data in gfiphc, maybe not all examples fully tested, but vignettes cover a lot of the code.
