### ISSUE TITLE
IPHC survey next steps

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfiphc#7]
- [x] Builds figure, just not properly accessing the early IPHC data (e.g. Yelloweye) - think a species-naming issue (or I need to clear out a cache - but doubtful as figure has been updated, can compare versions). Big Skate not getting 1998-2002 values even though they're there (but none earlier; Sat 5:30).
- [x] Get non-existent species (e.g. Basking Shark) to return a row of NA's in final data frame
- [x] Loop through all the Type A and Type B species, adding new IPHC-specific names for the early ones
- [x] Add Type B species to iphc-spp-names.csv
- [ ] Decide what to do about Eelpout (and maybe others) - they're not species-specific in early IPHC
- [x] Write up text in gfsynopsis
- [x] Merge functions into gfplot
- [ ] Replace (remove) IPHC queries in other gfplot functions as necessary
- [ ] Remove plot_iphc_index() (think that plot_survey_index() may work anyway)
- [x] Unhardwire num_sets = 130, and keep track of from early call
- [x] Run check() and tidy up as necessary (especially if Travis still being cranky)
- [ ] Amend to include hook competition calculations
- [x] May need "Hook with Bait" in iphc-spp-names.csv
- [x] Create SQL query(s) needed for hook competition
- [ ] Amend R functions for hook competition (probably just change N_it early on), or keep track of both
- [ ] Compare hook competition with no competition results, include some if necessary
- [x] Get all into the main gfplot calls
- [x] Re-run queries for all species to get all the IPHC data and build the full figures
- [ ] Comment on any particular figures as necessary (?)
- [ ] Comment out `  skip("Skipping tests to save time on DFO Windows Computer")` in `test-get-data.R`; put that in to save time while developing (and Travis not working), since it takes ages.
- [x] rstan back to >=2.18.1 at some point
- [x] gfsynposis make-pages.R - see AME note for inserting the IPHC data

**Comment by andrew-edwards** [comment]
In third from last bullet, `test-get-data.R` is mentioned but doesn't seem to be in gfiphc.

**Comment by andrew-edwards** [comment]
It's in gfplot if needed.

**Comment by seananderson** [comment]
It would be in gfplot, although a more up to date one (missing the iphc stuff) is in gfdata. tests/testthat

Yes, I see your latest comment now.

I should pull that iphc stuff (and all get data stuff eventually) from gfplot.

**Comment by andrew-edwards** [comment]
Mostly done or no longer needed. Eelpouts don't seem to have any species-specific data, so probably not useful anyway.
